weights: ''
cfg: ./models/custom_yolov5s.yaml
data: /content/drive/My Drive/Factory Security Automation/dataset/Fire_Smoke/data.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 16
img_size:
  - 416
  - 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
name: yolov5s_results
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
log_imgs: 0
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
